version: '3.8'

services:     
  dbmysqldocker:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'jspringtodo'
      MYSQL_USER: 'javaspringtodo'
        #double $$ for escaping $ character
      MYSQL_PASSWORD: /run/secrets/dba_mysql
      # Password for root access
      MYSQL_ROOT_PASSWORD: /run/secrets/admin_mysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    container_name: mysqldocker
    networks:
      - jsbtodorest
    volumes:
      - jspringtodo-mysqlvol:/var/lib/mysql
    secrets:
      - dba_mysql
      - admin_mysql

volumes:
  jspringtodo-mysqlvol:

secrets:
  dba_mysql:
    file: ./dba_mysql.txt
  admin_mysql:
    file: ./admin_mysql.txt

networks:
  jsbtodorest:
    driver: bridge
