version: '3.8'

services:     
  dbmysqldocker:
    image: mysql:8.1.0
    restart: always
    env_file:
      - ./mysqlinit/.envmysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    container_name: mysqldocker
    networks:
      - mysqldockernetwork
    volumes:
      - jsbtododata:/var/lib/mysql
      - ./mysqlinit/jsbtodoschema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  jsbtododata:

networks:
  mysqldockernetwork:
    name: mysqldockernetwork
    driver: bridge
