version: '3.8'
  #based on: 
  #https://geshan.com.np/blog/2021/12/docker-postgres/
  #https://docs.docker.com/compose/use-secrets/

services:
  dbpgdocker:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: /run/secrets/dba_pg
    ports:
      # <Port exposed> : <pg Port running inside container>
      - '5435:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
    container_name: pgdocker
    networks:
      - pgdockernetwork
    volumes:
      - pgvol:/var/lib/postgresql/data
    secrets:
      - dba_pg

volumes:
  pgvol:

secrets:
  dba_pg:
    file: dba_pg.txt

networks:
  pgdockernetwork:
    driver: bridge
