version: '3.8'
  #based on: 
  #https://geshan.com.np/blog/2021/12/docker-postgres/
  #https://docs.docker.com/compose/use-secrets/

services:
  dbpgdocker:
    image: postgres:14.1-alpine
    restart: always
    #postgres user is the default admin
    #the intention is to set a custom password
    env_file:
      - ./pginit/.envpg
    ports:
      # <Port exposed> : <pg Port running inside container>
      - '5435:5432'
    container_name: pgdocker
    networks:
      - pgdockernetwork
    volumes:
      #mapping data from container to the host computer default location
      - gobankdata:/var/lib/postgresql/data
      - ./pginit/gobankschema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  #volume's name
  gobankdata:

networks:
  pgdockernetwork:
    name: pgdockernetwork
    driver: bridge
