version: '3.8'
  #based on: 
  #https://geshan.com.np/blog/2021/12/docker-postgres/
  #https://docs.docker.com/compose/use-secrets/

services:
  dbpgdocker:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.envpg
    ports:
      # <Port exposed> : <pg Port running inside container>
      - '5435:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
    container_name: pgdocker
    networks:
      - pgdockernetwork
    volumes:
      - gobankdata:/var/lib/postgresql/data
      - ./pginit.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  pgdockernetwork:
    name: pgdockernetwork
    driver: bridge
