version: '3.8'
  #based on: 
  #https://geshan.com.np/blog/2021/12/docker-postgres/
  #https://docs.docker.com/compose/use-secrets/

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: /run/secrets/dba_pg
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5435:5435'
    expose:
      # Opens port 3306 on the container
      # Where our data will be persisted
    container_name: pg-docker-local
    networks:
      - pgnetwork
    volumes:
      - pgvol:/var/lib/postgresql/data
    secrets:
      - dba_pg

volumes:
  pgvol:

secrets:
  dba_pg:
    file: dba_pg.txt

networks:
  pgnetwork:
    driver: bridge
